---
title: "Big Mac Index 2023 January"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    includes:
      after_body: after-body.html
---

```{r setup, include=FALSE}
library(flexdashboard)
chartC=readRDS("./chartC.Rds")
chartB=readRDS("./chartB.Rds")
chartA=readRDS("./chartA.Rds")
bigMacData=readRDS("./bigMacData.Rds")
#chartA=readRDS("../week10/chartA.Rds")
#bigMacData=readRDS("../week10/bigMacData.Rds")
```


```{r}
htmltools::tags$script(
  id="chartB-tracemap",
  type="application/json",
  chartB$tracemap |> jsonlite::toJSON(auto_unbox = T)
)
htmltools::tags$script(
  id="chartC-tracemap",
  type="application/json",
  chartC$tracemap |> jsonlite::toJSON(auto_unbox = T)
)
htmltools::tags$script(
  id="chartB-x",
  type="application/json",
  chartB$allYears |> jsonlite::toJSON(auto_unbox = T)
)
# htmltools::includeScript("./js/helper.js")
```



Column {data-width=150}
-----------------------------------------------------------------------

### Chart A

```{r}
chartA$tb0$elementId <- "widget-chartA"
chartA$tb0 |>
  htmlwidgets::onRender(readLines("./chartA.js"))
```



Column {data-width=350}
-----------------------------------------------------------------------

### Chart B


```{r}
chartB$dropdownMenu
```

```{r chartB}
chartB$highlightWithSplit$elementId <- "widget-chartB"
chartB$highlightWithSplit  |>
  htmlwidgets::onRender(readLines("./chartB.js"))
# chartB$highlight |>
#   econIDV::get_traceInfo()
```

### Chart C

```{r chartC}
chartC$complete$trace4highlight$withScatterGL_highlightGrey |>
  htmlwidgets::onRender(readLines("./chartC.js"))
```

